site_name: Liam
site_url: https://lamdv.github.io/
theme: 
  name: material 
  feature:
    tabs: true
remote_branch: master
repo_url: https://github.com/lamdv/lamdv.github.io
edit_uri: edit/source/docs/
docs_dir: docs
site_dir: site
pages:
  - Home: 'index.md'
  - Curriculum Vitae: 'CV.md'
  - Scientific Journey:
    - 'Hành trình khoa học: Python và R': 'Scientific Journey\\intro.md'
    - '(Những) ngày đầu tiên': 'Scientific Journey\\day-one-ish.md'
    - 'Ghi chú bằng Markdown': 'Scientific Journey\\day-two-documentation-markdown.md'
  - Thought:
  #   - 'Nov 28 2017': 'Thought\\nov-28-17.md'
  #   - 'Mỏi': 'Thought\\tiresome.md'
    - 'The Death of Expertise' : 'Thought\\the-death-of-expertise.md'
    - 'Về chuyện viết lách' : 'Thought\\on-writing.md'
    # - 'AI Presentation - Agoda' : 'Thought\\presentation.md'
    - 'Tiêu chuẩn Tạo Tác' : 'taotac\\a-survey-of-mounting.md'
markdown_extensions:
    # - pymdownx.emoji:
    #     emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - mdx_math 